version: "3.9"

services:
  flask:
    container_name: flask
    build: ./flask/
    volumes:
      - ./flask/:/app

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 5555:80
    depends_on:
      - flask